CREATE DATABASE IF NOT EXISTS meu_vector_db;
USE meu_vector_db;

CREATE TABLE IF NOT EXISTS vector_documentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    conteudo TEXT NOT NULL,
    embedding VECTOR(768) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Mock VECTOR_DISTANCE for local development (since it's only available in MySQL HeatWave)
DROP FUNCTION IF EXISTS VECTOR_DISTANCE;
CREATE FUNCTION VECTOR_DISTANCE(v1 BLOB, v2 BLOB, metric VARCHAR(50)) 
RETURNS DOUBLE DETERMINISTIC 
RETURN 0.5;

